version: '3'
services:
  es:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    environment:
      - node.name=es
      - xpack.security.enabled=false
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esData:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  app:
    container_name: app
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - es
    ports:
      - "8080:8080"

  postgres:
    container_name: postgres
    image: postgres:9.6
    environment:
      - "POSTGRES_DB=openbox"
      - "POSTGRES_USER=root"
      - "POSTGRES_PASSWORD=root"
    ports:
      - "54325:5432"

volumes:
  esData:
    driver: local
